package com.easyride.payment_service.dto;

import com.easyride.payment_service.model.PaymentMethodType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Data
public class AddPaymentMethodRequestDto {
    // Passenger ID will come from authenticated principal, not request body
    // private Long passengerId;

    @NotNull(message = "支付方式类型不能为空")
    private PaymentMethodType methodType;

    // This 'nonce' or 'token' is generated by the client-side SDK of the payment
    // gateway
    // (e.g., Stripe Elements, PayPal JS SDK) after collecting card details
    // securely.
    // It represents the one-time-use token for the card details.
    @NotBlank(message = "支付网关令牌 (nonce) 不能为空")
    private String paymentGatewayNonce; // e.g., Stripe's payment_method_ID or source_ID, PayPal's nonce

    private boolean isDefault = false;

    // Optional: For card display if gateway nonce doesn't provide it (some might)
    // These are NOT full card details.
    private String cardLastFour; // May be derived by backend after token processing with gateway
    private String cardBrand; // May be derived
    // private Integer expiryMonth;
    // private Integer expiryYear;

    // Optional billing details if not captured by gateway or needed for specific
    // processing
    private String billingName;
    // ... other billing address fields if needed
}