server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: your_mysql_username
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-issuer.com/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# PayPal Configuration
paypal:
  client-id: your_paypal_client_id
  client-secret: your_paypal_client_secret
  mode: sandbox # or live

# Stripe Configuration (for credit card payments)
stripe:
  api-key: your_stripe_api_key
