server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: admin
    password: pa$$word

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your_jwt_secret_key
  expiration: 604800000  # 7 days in milliseconds

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
