#  配置了服务器端口为 8081（避免与其他服务端口冲突）。
#    配置了数据库连接信息，需要根据实际情况修改用户名和密码。
#  设置了 JPA 的配置，ddl-auto: update 会自动更新数据库表结构。


  server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: your_db_username
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
