server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 2721388927
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: your_very_long_jwt_secret_key_that_is_at_least_32_characters_long
  expiration: 604800000  # 7 days in milliseconds

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: analytics-producer-group
  consumer:
    group: analytics-consumer-group
